server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  paths-to-match: /**

spring:
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/clients_service_db;
    username: ${DB_USER}
    password: ${DB_PASSWORD}
